### ISSUE TITLE
Incompatible with Mantle (Tconstruct required library)

### ISSUE THREAD

**Issue by Eranderil** [KurodaAkira/RPG-Hud#50] opened 2018-07-15 17:00 UTC
When using Tconstruct with this mod, only vanilla hearts will render. Did thorough testing to find this out, ripping out mods until RPGhud fixed. Got down to Mantle with no change, then when I removed Mantle, RPG hud straightened out. Even attempting to force the render didn't work in my testing. Considering the popularity of Tconstruct, this should be top of the list for fixing, as it will impact the popularity of RPG hud negativly.

**Comment by Kordov19** [comment] 2018-07-18 03:04
![jre1 8 0_171 screenshot 2018 07 17 - 20 03 10 89](https://user-images.githubusercontent.com/36905372/42856981-8679f6fc-89fc-11e8-85bf-ccdf4468343c.png)


Like this?

**Comment by Raelzaryn** [comment] 2018-07-18 03:17
Duplicate of #29

**Closed as completed by Raelzaryn** 2018-07-18 03:17 UTC
Labels: duplicate
